---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.spring.io/vcs-url: https://github.com/carlosmarin88/fruits-spring.git
  labels:
    app.kubernetes.io/name: rest-json-fruit-spring
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: rest-json-fruit-spring
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.spring.io/vcs-url: https://github.com/carlosmarin88/fruits-spring.git
  labels:
    app.kubernetes.io/name: rest-json-fruit-spring
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: rest-json-fruit-spring
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: rest-json-fruit-spring
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.spring.io/vcs-url: https://github.com/carlosmarin88/fruits-spring.git
  labels:
    app.kubernetes.io/name: rest-json-fruit-spring
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: rest-json-fruit-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rest-json-fruit-spring
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.spring.io/vcs-url: https://github.com/carlosmarin88/fruits-spring.git
      labels:
        app.kubernetes.io/name: rest-json-fruit-spring
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: carlosmarin88/fruits-spring:latest
        imagePullPolicy: Always
        name: rest-json-fruit-spring
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      serviceAccount: rest-json-fruit-spring
